# Copyright (C) 2026 Delinquants
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
---
namespace: delinquants
name: server
readme: README.md
version: 0.1.0
authors:
  - Delinquants
description: A generic-purpose collection of roles used to deploy webservers.
tags:
  - infrastructure
  - linux
  - networking
  - security
license:
  - GPL-3.0-or-later
repository: https://github.com/Delinquants/ansible-deployment
